syntax = "proto2";

service Client_Interface {
    // Client requests a list of available parking spots along with prices
    rpc getAvailablespots (AvailablespotReq) returns (AvailablespotResp) {}

    // Client makes a reservation for a specific parking spot in a specific lot
    rpc makeReservation (ResReq) returns (ResResp) {}
    // gets reservations made by a certain client.
    rpc getReservations (ResGetReq) returns (ResGetResp) {}
    // edits a reservation in the database
    rpc editRes (ResEditReq) returns (ResEditResp) {}

}

// Available spots request specifies which parking lot, time, and duration
message AvailablespotReq {
    required string lotID = 1;
    required string datetime = 2;
    required int32 duration = 3;
}

// Available spot response returns list of available spots in that parking lot as JSON
message AvailablespotResp {
    required string availablespots = 1;
}

// Reservation request specifies which parking lot and spot, userID, date and time, duration, and payment info
message ResReq {
    required string lotID = 1;
    required string spotID = 2;
    required string plateNum = 3;
    required string paymentInfo = 4;
    required string datetime = 5;
    required int32 duration = 6;
}

// Reservation response is success/fail
message ResResp {
    required bool success = 1;
    required string resID = 2;
    optional string errorCode = 3;
}
// UserId to filter reservations from. If resID is provided, will return just that reservation's information
message ResGetReq{
    required string plateNum = 1;
    optional string resID = 2;
}
// Returns JSON formatted string
message ResGetResp{
    required string reservations = 1;
}

message ResEditReq{
    required string resID = 1;
    optional string datetime = 2;
    optional int32 duration = 3;
    optional bool cancel = 4;
}

message ResEditResp{
    required string resID = 1;
    required bool success = 2;
    optional string errorCode = 3;
}