# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import client_interface_pb2 as client__interface__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in client_interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Client_InterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getAvailablespots = channel.unary_unary(
                '/Client_Interface/getAvailablespots',
                request_serializer=client__interface__pb2.AvailablespotReq.SerializeToString,
                response_deserializer=client__interface__pb2.AvailablespotResp.FromString,
                _registered_method=True)
        self.makeReservation = channel.unary_unary(
                '/Client_Interface/makeReservation',
                request_serializer=client__interface__pb2.ResReq.SerializeToString,
                response_deserializer=client__interface__pb2.ResResp.FromString,
                _registered_method=True)


class Client_InterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getAvailablespots(self, request, context):
        """Client requests a list of available parking spots
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def makeReservation(self, request, context):
        """Client makes a reservation for a specific parking spot in a specific lot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Client_InterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getAvailablespots': grpc.unary_unary_rpc_method_handler(
                    servicer.getAvailablespots,
                    request_deserializer=client__interface__pb2.AvailablespotReq.FromString,
                    response_serializer=client__interface__pb2.AvailablespotResp.SerializeToString,
            ),
            'makeReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.makeReservation,
                    request_deserializer=client__interface__pb2.ResReq.FromString,
                    response_serializer=client__interface__pb2.ResResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Client_Interface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Client_Interface', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Client_Interface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getAvailablespots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Client_Interface/getAvailablespots',
            client__interface__pb2.AvailablespotReq.SerializeToString,
            client__interface__pb2.AvailablespotResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def makeReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Client_Interface/makeReservation',
            client__interface__pb2.ResReq.SerializeToString,
            client__interface__pb2.ResResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
