syntax = "proto2";

service Database_Interface {
    // Requests list of available spots
    rpc getAvailableSpots (AvailableSpotsReq) returns (AvailableSpotsResp) {}
    // Updates list of reservations
    rpc updateReservations (UpdateResReq) returns (UpdateResResp) {}
    // Updates list of transactions made
    rpc updateTransaction (TransUpdateReq) returns (TransUpdateResp) {}
}

// Specifies which parking lot
message AvailableSpotsReq {
    required string lotID = 1;
    
}

// Returns list of comma separated parking spot IDs
message AvailableSpotsResp {
    required string availableSpots = 1;
}

// Request specifies reservation to be added/changed
message UpdateResReq {
    required string resID = 1;
    required string lotID = 2;
    required string spotID = 3;
    required string uID = 4;
    required string datetime = 5;
    required string duration = 6;
}

// Response returns success/fail and resID
message UpdateResResp {
    required bool success = 1;
    required bool resID = 2;
}

// Transaction update request consists of related reservation ID, user ID, and payment info
message TransUpdateReq {
    required string resID = 1;
    required string uID = 2;
    required string paymentInfo = 3;
    required string transID = 4;
    required string val = 5;
}

// Transaction update response consists of success/fail and transaction ID
message TransUpdateResp {
    required string transID = 1;
    required bool success = 2;
}