# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database_interface.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'database_interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x61tabase_interface.proto\"\"\n\x11\x41vailableSpotsReq\x12\r\n\x05lotID\x18\x01 \x02(\t\",\n\x12\x41vailableSpotsResp\x12\x16\n\x0e\x61vailableSpots\x18\x01 \x02(\t\"m\n\x0cUpdateResReq\x12\r\n\x05resID\x18\x01 \x02(\t\x12\r\n\x05lotID\x18\x02 \x02(\t\x12\x0e\n\x06spotID\x18\x03 \x02(\t\x12\x0b\n\x03uID\x18\x04 \x02(\t\x12\x10\n\x08\x64\x61tetime\x18\x05 \x02(\t\x12\x10\n\x08\x64uration\x18\x06 \x02(\t\"/\n\rUpdateResResp\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\r\n\x05resID\x18\x02 \x02(\x08\"_\n\x0eTransUpdateReq\x12\r\n\x05resID\x18\x01 \x02(\t\x12\x0b\n\x03uID\x18\x02 \x02(\t\x12\x13\n\x0bpaymentInfo\x18\x03 \x02(\t\x12\x0f\n\x07transID\x18\x04 \x02(\t\x12\x0b\n\x03val\x18\x05 \x02(\t\"3\n\x0fTransUpdateResp\x12\x0f\n\x07transID\x18\x01 \x02(\t\x12\x0f\n\x07success\x18\x02 \x02(\x08\x32\xc5\x01\n\x12\x44\x61tabase_Interface\x12>\n\x11getAvailableSpots\x12\x12.AvailableSpotsReq\x1a\x13.AvailableSpotsResp\"\x00\x12\x35\n\x12updateReservations\x12\r.UpdateResReq\x1a\x0e.UpdateResResp\"\x00\x12\x38\n\x11updateTransaction\x12\x0f.TransUpdateReq\x1a\x10.TransUpdateResp\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVAILABLESPOTSREQ']._serialized_start=28
  _globals['_AVAILABLESPOTSREQ']._serialized_end=62
  _globals['_AVAILABLESPOTSRESP']._serialized_start=64
  _globals['_AVAILABLESPOTSRESP']._serialized_end=108
  _globals['_UPDATERESREQ']._serialized_start=110
  _globals['_UPDATERESREQ']._serialized_end=219
  _globals['_UPDATERESRESP']._serialized_start=221
  _globals['_UPDATERESRESP']._serialized_end=268
  _globals['_TRANSUPDATEREQ']._serialized_start=270
  _globals['_TRANSUPDATEREQ']._serialized_end=365
  _globals['_TRANSUPDATERESP']._serialized_start=367
  _globals['_TRANSUPDATERESP']._serialized_end=418
  _globals['_DATABASE_INTERFACE']._serialized_start=421
  _globals['_DATABASE_INTERFACE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
