# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import database_interface_pb2 as database__interface__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in database_interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Database_InterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getAvailableSpots = channel.unary_unary(
                '/Database_Interface/getAvailableSpots',
                request_serializer=database__interface__pb2.AvailableSpotsReq.SerializeToString,
                response_deserializer=database__interface__pb2.AvailableSpotsResp.FromString,
                _registered_method=True)
        self.updateReservations = channel.unary_unary(
                '/Database_Interface/updateReservations',
                request_serializer=database__interface__pb2.UpdateResReq.SerializeToString,
                response_deserializer=database__interface__pb2.UpdateResResp.FromString,
                _registered_method=True)
        self.updateTransaction = channel.unary_unary(
                '/Database_Interface/updateTransaction',
                request_serializer=database__interface__pb2.TransUpdateReq.SerializeToString,
                response_deserializer=database__interface__pb2.TransUpdateResp.FromString,
                _registered_method=True)


class Database_InterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getAvailableSpots(self, request, context):
        """Requests list of available spots
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateReservations(self, request, context):
        """Updates list of reservations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateTransaction(self, request, context):
        """Updates list of transactions made
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Database_InterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getAvailableSpots': grpc.unary_unary_rpc_method_handler(
                    servicer.getAvailableSpots,
                    request_deserializer=database__interface__pb2.AvailableSpotsReq.FromString,
                    response_serializer=database__interface__pb2.AvailableSpotsResp.SerializeToString,
            ),
            'updateReservations': grpc.unary_unary_rpc_method_handler(
                    servicer.updateReservations,
                    request_deserializer=database__interface__pb2.UpdateResReq.FromString,
                    response_serializer=database__interface__pb2.UpdateResResp.SerializeToString,
            ),
            'updateTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.updateTransaction,
                    request_deserializer=database__interface__pb2.TransUpdateReq.FromString,
                    response_serializer=database__interface__pb2.TransUpdateResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Database_Interface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Database_Interface', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Database_Interface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getAvailableSpots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Database_Interface/getAvailableSpots',
            database__interface__pb2.AvailableSpotsReq.SerializeToString,
            database__interface__pb2.AvailableSpotsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateReservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Database_Interface/updateReservations',
            database__interface__pb2.UpdateResReq.SerializeToString,
            database__interface__pb2.UpdateResResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Database_Interface/updateTransaction',
            database__interface__pb2.TransUpdateReq.SerializeToString,
            database__interface__pb2.TransUpdateResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
