# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import database_interface_pb2 as database__interface__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in database_interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Database_InterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getAvailableSpots = channel.unary_unary(
                '/Database_Interface/getAvailableSpots',
                request_serializer=database__interface__pb2.AvailableSpotsReq.SerializeToString,
                response_deserializer=database__interface__pb2.AvailableSpotsResp.FromString,
                _registered_method=True)
        self.updateReservations = channel.unary_unary(
                '/Database_Interface/updateReservations',
                request_serializer=database__interface__pb2.UpdateResReq.SerializeToString,
                response_deserializer=database__interface__pb2.UpdateResResp.FromString,
                _registered_method=True)
        self.getReservations = channel.unary_unary(
                '/Database_Interface/getReservations',
                request_serializer=database__interface__pb2.GetResReq.SerializeToString,
                response_deserializer=database__interface__pb2.GetResResp.FromString,
                _registered_method=True)
        self.createTransaction = channel.unary_unary(
                '/Database_Interface/createTransaction',
                request_serializer=database__interface__pb2.TransCreateReq.SerializeToString,
                response_deserializer=database__interface__pb2.TransCreateResp.FromString,
                _registered_method=True)
        self.getTransactions = channel.unary_unary(
                '/Database_Interface/getTransactions',
                request_serializer=database__interface__pb2.TransGetReq.SerializeToString,
                response_deserializer=database__interface__pb2.TransGetResp.FromString,
                _registered_method=True)
        self.updateSpotOccupancy = channel.unary_unary(
                '/Database_Interface/updateSpotOccupancy',
                request_serializer=database__interface__pb2.spotUpdateReq.SerializeToString,
                response_deserializer=database__interface__pb2.spotUpdateResp.FromString,
                _registered_method=True)


class Database_InterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getAvailableSpots(self, request, context):
        """Requests list of available spots
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateReservations(self, request, context):
        """Updates list of reservations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getReservations(self, request, context):
        """gets a list of reservations made by the user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createTransaction(self, request, context):
        """creates a new transaction, used by transaction handler
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTransactions(self, request, context):
        """Returns a list of transactions for the specified reservation/user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateSpotOccupancy(self, request, context):
        """Updates the occupancy of a spot given spotID and lotID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Database_InterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getAvailableSpots': grpc.unary_unary_rpc_method_handler(
                    servicer.getAvailableSpots,
                    request_deserializer=database__interface__pb2.AvailableSpotsReq.FromString,
                    response_serializer=database__interface__pb2.AvailableSpotsResp.SerializeToString,
            ),
            'updateReservations': grpc.unary_unary_rpc_method_handler(
                    servicer.updateReservations,
                    request_deserializer=database__interface__pb2.UpdateResReq.FromString,
                    response_serializer=database__interface__pb2.UpdateResResp.SerializeToString,
            ),
            'getReservations': grpc.unary_unary_rpc_method_handler(
                    servicer.getReservations,
                    request_deserializer=database__interface__pb2.GetResReq.FromString,
                    response_serializer=database__interface__pb2.GetResResp.SerializeToString,
            ),
            'createTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.createTransaction,
                    request_deserializer=database__interface__pb2.TransCreateReq.FromString,
                    response_serializer=database__interface__pb2.TransCreateResp.SerializeToString,
            ),
            'getTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.getTransactions,
                    request_deserializer=database__interface__pb2.TransGetReq.FromString,
                    response_serializer=database__interface__pb2.TransGetResp.SerializeToString,
            ),
            'updateSpotOccupancy': grpc.unary_unary_rpc_method_handler(
                    servicer.updateSpotOccupancy,
                    request_deserializer=database__interface__pb2.spotUpdateReq.FromString,
                    response_serializer=database__interface__pb2.spotUpdateResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Database_Interface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Database_Interface', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Database_Interface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getAvailableSpots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Database_Interface/getAvailableSpots',
            database__interface__pb2.AvailableSpotsReq.SerializeToString,
            database__interface__pb2.AvailableSpotsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateReservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Database_Interface/updateReservations',
            database__interface__pb2.UpdateResReq.SerializeToString,
            database__interface__pb2.UpdateResResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getReservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Database_Interface/getReservations',
            database__interface__pb2.GetResReq.SerializeToString,
            database__interface__pb2.GetResResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Database_Interface/createTransaction',
            database__interface__pb2.TransCreateReq.SerializeToString,
            database__interface__pb2.TransCreateResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Database_Interface/getTransactions',
            database__interface__pb2.TransGetReq.SerializeToString,
            database__interface__pb2.TransGetResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateSpotOccupancy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Database_Interface/updateSpotOccupancy',
            database__interface__pb2.spotUpdateReq.SerializeToString,
            database__interface__pb2.spotUpdateResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
