# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iot_interface.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'iot_interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13iot_interface.proto\"\x1f\n\x07\x46reeMsg\x12\x14\n\x0cserialNumber\x18\x01 \x02(\x05\"#\n\x0bOccupiedMsg\x12\x14\n\x0cserialNumber\x18\x01 \x02(\x05\"T\n\x06IoTAck\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x14\n\x0cserialNumber\x18\x02 \x02(\x05\x12\x14\n\x0cstateChanged\x18\x03 \x02(\x08\x12\r\n\x05\x65rror\x18\x04 \x01(\t2]\n\rIoT_Interface\x12!\n\nreportFree\x12\x08.FreeMsg\x1a\x07.IoTAck\"\x00\x12)\n\x0ereportOccupied\x12\x0c.OccupiedMsg\x1a\x07.IoTAck\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iot_interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FREEMSG']._serialized_start=23
  _globals['_FREEMSG']._serialized_end=54
  _globals['_OCCUPIEDMSG']._serialized_start=56
  _globals['_OCCUPIEDMSG']._serialized_end=91
  _globals['_IOTACK']._serialized_start=93
  _globals['_IOTACK']._serialized_end=177
  _globals['_IOT_INTERFACE']._serialized_start=179
  _globals['_IOT_INTERFACE']._serialized_end=272
# @@protoc_insertion_point(module_scope)
