# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import iot_interface_pb2 as iot__interface__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in iot_interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IoT_InterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reportFree = channel.unary_unary(
                '/IoT_Interface/reportFree',
                request_serializer=iot__interface__pb2.FreeMsg.SerializeToString,
                response_deserializer=iot__interface__pb2.IoTAck.FromString,
                _registered_method=True)
        self.reportOccupied = channel.unary_unary(
                '/IoT_Interface/reportOccupied',
                request_serializer=iot__interface__pb2.OccupiedMsg.SerializeToString,
                response_deserializer=iot__interface__pb2.IoTAck.FromString,
                _registered_method=True)


class IoT_InterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reportFree(self, request, context):
        """Sensor reports a spot became free
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reportOccupied(self, request, context):
        """Sensor reports a spot became occupied
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IoT_InterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reportFree': grpc.unary_unary_rpc_method_handler(
                    servicer.reportFree,
                    request_deserializer=iot__interface__pb2.FreeMsg.FromString,
                    response_serializer=iot__interface__pb2.IoTAck.SerializeToString,
            ),
            'reportOccupied': grpc.unary_unary_rpc_method_handler(
                    servicer.reportOccupied,
                    request_deserializer=iot__interface__pb2.OccupiedMsg.FromString,
                    response_serializer=iot__interface__pb2.IoTAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IoT_Interface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('IoT_Interface', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IoT_Interface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reportFree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/IoT_Interface/reportFree',
            iot__interface__pb2.FreeMsg.SerializeToString,
            iot__interface__pb2.IoTAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def reportOccupied(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/IoT_Interface/reportOccupied',
            iot__interface__pb2.OccupiedMsg.SerializeToString,
            iot__interface__pb2.IoTAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
