syntax = "proto2";

service Pricing_Calculator {
    // Client Interface requests a price for a spot
    rpc getPrice (PriceReq) returns (PriceResp) {}

}

// Price Request specifies which lot and number of available spots. datetime is DD/MM/YYYY HH:MM, duration is in minutes
message PriceReq {
    required int32 lotID = 1;
    required int32 remainingSpots = 2;
    required int32 totalSpots = 3;
    required string datetime = 4;
    required int32 duration = 5;
}

// Price Response returns a single price for the whole lot
message PriceResp {
    optional float price = 1;
}