# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing_calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pricing_calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18pricing_calculator.proto\"i\n\x08PriceReq\x12\r\n\x05lotID\x18\x01 \x02(\x05\x12\x16\n\x0eremainingSpots\x18\x02 \x02(\x05\x12\x12\n\ntotalSpots\x18\x03 \x02(\x05\x12\x10\n\x08\x64\x61tetime\x18\x04 \x02(\t\x12\x10\n\x08\x64uration\x18\x05 \x02(\x05\"\x1a\n\tPriceResp\x12\r\n\x05price\x18\x01 \x01(\x02\x32\x39\n\x12Pricing_Calculator\x12#\n\x08getPrice\x12\t.PriceReq\x1a\n.PriceResp\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pricing_calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICEREQ']._serialized_start=28
  _globals['_PRICEREQ']._serialized_end=133
  _globals['_PRICERESP']._serialized_start=135
  _globals['_PRICERESP']._serialized_end=161
  _globals['_PRICING_CALCULATOR']._serialized_start=163
  _globals['_PRICING_CALCULATOR']._serialized_end=220
# @@protoc_insertion_point(module_scope)
