syntax = "proto2";

service Pricing_Calculator {
    // Client Interface requests a price for a spot
    rpc getPrice (PriceReq) returns (PriceResp) {}

}

// Price Request specifies which lot and number of available spots. datetime is DD/MM/YYYY HH:MM, duration is in minutes
message PriceReq {
    required string lotID = 1;
    required int32 remainingSpots = 2;
    required string datetime = 3;
    required int32 duration = 4;
}

// Price Response returns a single price for the whole lot
message PriceResp {
    required float price = 1;
}