syntax = "proto2";

service Pricing_Calculator {
    // Client Interface requests a price for a spot
    rpc getPrice (PriceReq) returns (PriceResp) {}

}

// Price Request specifies which lot and available spots. Spots is formatted as JSON, datetime is DD/MM/YYYY HH:MM, duration is in minutes
message PriceReq {
    required string lotID = 1;
    repeated string spots = 2;
    required string datetime = 3;
    required int32 duration = 4;
}

// Price Response returns the price for each available spot in the lot as a JSON
message PriceResp {
    required string prices = 1;
}