# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transaction_handler_pb2 as transaction__handler__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in transaction_handler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Transaction_HandlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.makePayment = channel.unary_unary(
                '/Transaction_Handler/makePayment',
                request_serializer=transaction__handler__pb2.transReq.SerializeToString,
                response_deserializer=transaction__handler__pb2.transResp.FromString,
                _registered_method=True)


class Transaction_HandlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def makePayment(self, request, context):
        """Makes a payment for a reservation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Transaction_HandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'makePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.makePayment,
                    request_deserializer=transaction__handler__pb2.transReq.FromString,
                    response_serializer=transaction__handler__pb2.transResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transaction_Handler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Transaction_Handler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Transaction_Handler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def makePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Transaction_Handler/makePayment',
            transaction__handler__pb2.transReq.SerializeToString,
            transaction__handler__pb2.transResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
