/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v7.34.1
// source: client_interface.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as client_interface_pb from './client_interface_pb'; // proto import: "client_interface.proto"


export class Client_InterfaceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorgetAvailablespots = new grpcWeb.MethodDescriptor(
    '/Client_Interface/getAvailablespots',
    grpcWeb.MethodType.UNARY,
    client_interface_pb.AvailablespotReq,
    client_interface_pb.AvailablespotResp,
    (request: client_interface_pb.AvailablespotReq) => {
      return request.serializeBinary();
    },
    client_interface_pb.AvailablespotResp.deserializeBinary
  );

  getAvailablespots(
    request: client_interface_pb.AvailablespotReq,
    metadata?: grpcWeb.Metadata | null): Promise<client_interface_pb.AvailablespotResp>;

  getAvailablespots(
    request: client_interface_pb.AvailablespotReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: client_interface_pb.AvailablespotResp) => void): grpcWeb.ClientReadableStream<client_interface_pb.AvailablespotResp>;

  getAvailablespots(
    request: client_interface_pb.AvailablespotReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: client_interface_pb.AvailablespotResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Client_Interface/getAvailablespots',
        request,
        metadata || {},
        this.methodDescriptorgetAvailablespots,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Client_Interface/getAvailablespots',
    request,
    metadata || {},
    this.methodDescriptorgetAvailablespots);
  }

  methodDescriptormakeReservation = new grpcWeb.MethodDescriptor(
    '/Client_Interface/makeReservation',
    grpcWeb.MethodType.UNARY,
    client_interface_pb.ResReq,
    client_interface_pb.ResResp,
    (request: client_interface_pb.ResReq) => {
      return request.serializeBinary();
    },
    client_interface_pb.ResResp.deserializeBinary
  );

  makeReservation(
    request: client_interface_pb.ResReq,
    metadata?: grpcWeb.Metadata | null): Promise<client_interface_pb.ResResp>;

  makeReservation(
    request: client_interface_pb.ResReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: client_interface_pb.ResResp) => void): grpcWeb.ClientReadableStream<client_interface_pb.ResResp>;

  makeReservation(
    request: client_interface_pb.ResReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: client_interface_pb.ResResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Client_Interface/makeReservation',
        request,
        metadata || {},
        this.methodDescriptormakeReservation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Client_Interface/makeReservation',
    request,
    metadata || {},
    this.methodDescriptormakeReservation);
  }

}

