// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file client_interface.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file client_interface.proto.
 */
export const file_client_interface: GenFile = /*@__PURE__*/
  fileDesc("ChZjbGllbnRfaW50ZXJmYWNlLnByb3RvIkUKEEF2YWlsYWJsZXNwb3RSZXESDQoFbG90SUQYASACKAkSEAoIZGF0ZXRpbWUYAiACKAkSEAoIZHVyYXRpb24YAyACKAUiKwoRQXZhaWxhYmxlc3BvdFJlc3ASFgoOYXZhaWxhYmxlc3BvdHMYASACKAkibQoGUmVzUmVxEg0KBWxvdElEGAEgAigJEg4KBnNwb3RJRBgCIAIoCRILCgN1SUQYAyACKAkSEwoLcGF5bWVudEluZm8YBCACKAkSEAoIZGF0ZXRpbWUYBSACKAkSEAoIZHVyYXRpb24YBiACKAkiKQoHUmVzUmVzcBIPCgdzdWNjZXNzGAEgAigIEg0KBXJlc0lEGAIgAigJMngKEENsaWVudF9JbnRlcmZhY2USPAoRZ2V0QXZhaWxhYmxlc3BvdHMSES5BdmFpbGFibGVzcG90UmVxGhIuQXZhaWxhYmxlc3BvdFJlc3AiABImCg9tYWtlUmVzZXJ2YXRpb24SBy5SZXNSZXEaCC5SZXNSZXNwIgA");

/**
 * Available spots request specifies which parking lot, time, and duration
 *
 * @generated from message AvailablespotReq
 */
export type AvailablespotReq = Message<"AvailablespotReq"> & {
  /**
   * @generated from field: required string lotID = 1;
   */
  lotID: string;

  /**
   * @generated from field: required string datetime = 2;
   */
  datetime: string;

  /**
   * @generated from field: required int32 duration = 3;
   */
  duration: number;
};

/**
 * Describes the message AvailablespotReq.
 * Use `create(AvailablespotReqSchema)` to create a new message.
 */
export const AvailablespotReqSchema: GenMessage<AvailablespotReq> = /*@__PURE__*/
  messageDesc(file_client_interface, 0);

/**
 * Available spot response returns list of available spots in that parking lot as JSON
 *
 * @generated from message AvailablespotResp
 */
export type AvailablespotResp = Message<"AvailablespotResp"> & {
  /**
   * @generated from field: required string availablespots = 1;
   */
  availablespots: string;
};

/**
 * Describes the message AvailablespotResp.
 * Use `create(AvailablespotRespSchema)` to create a new message.
 */
export const AvailablespotRespSchema: GenMessage<AvailablespotResp> = /*@__PURE__*/
  messageDesc(file_client_interface, 1);

/**
 * Reservation request specifies which parking lot and spot, userID, date and time, duration, and payment info
 *
 * @generated from message ResReq
 */
export type ResReq = Message<"ResReq"> & {
  /**
   * @generated from field: required string lotID = 1;
   */
  lotID: string;

  /**
   * @generated from field: required string spotID = 2;
   */
  spotID: string;

  /**
   * @generated from field: required string uID = 3;
   */
  uID: string;

  /**
   * @generated from field: required string paymentInfo = 4;
   */
  paymentInfo: string;

  /**
   * @generated from field: required string datetime = 5;
   */
  datetime: string;

  /**
   * @generated from field: required string duration = 6;
   */
  duration: string;
};

/**
 * Describes the message ResReq.
 * Use `create(ResReqSchema)` to create a new message.
 */
export const ResReqSchema: GenMessage<ResReq> = /*@__PURE__*/
  messageDesc(file_client_interface, 2);

/**
 * Reservation response is success/fail
 *
 * @generated from message ResResp
 */
export type ResResp = Message<"ResResp"> & {
  /**
   * @generated from field: required bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: required string resID = 2;
   */
  resID: string;
};

/**
 * Describes the message ResResp.
 * Use `create(ResRespSchema)` to create a new message.
 */
export const ResRespSchema: GenMessage<ResResp> = /*@__PURE__*/
  messageDesc(file_client_interface, 3);

/**
 * @generated from service Client_Interface
 */
export const Client_Interface: GenService<{
  /**
   * Client requests a list of available parking spots along with prices
   *
   * @generated from rpc Client_Interface.getAvailablespots
   */
  getAvailablespots: {
    methodKind: "unary";
    input: typeof AvailablespotReqSchema;
    output: typeof AvailablespotRespSchema;
  },
  /**
   * Client makes a reservation for a specific parking spot in a specific lot
   *
   * @generated from rpc Client_Interface.makeReservation
   */
  makeReservation: {
    methodKind: "unary";
    input: typeof ResReqSchema;
    output: typeof ResRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_client_interface, 0);

