// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file client_interface.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file client_interface.proto.
 */
export const file_client_interface: GenFile = /*@__PURE__*/
  fileDesc("ChZjbGllbnRfaW50ZXJmYWNlLnByb3RvIkUKEEF2YWlsYWJsZXNwb3RSZXESDQoFbG90SUQYASACKAUSEAoIZGF0ZXRpbWUYAiACKAkSEAoIZHVyYXRpb24YAyACKAUiKwoRQXZhaWxhYmxlc3BvdFJlc3ASFgoOYXZhaWxhYmxlc3BvdHMYASACKAkigQEKBlJlc1JlcRINCgVsb3RJRBgBIAIoBRIOCgZzcG90SUQYAiACKAUSEAoIcGxhdGVOdW0YAyACKAkSEwoLcGF5bWVudEluZm8YBCACKAkSEAoIZGF0ZXRpbWUYBSACKAkSEAoIZHVyYXRpb24YBiACKAUSDQoFcHJpY2UYByACKAIiPAoHUmVzUmVzcBIPCgdzdWNjZXNzGAEgAigIEg0KBXJlc0lEGAIgASgFEhEKCWVycm9yQ29kZRgDIAEoCSIsCglSZXNHZXRSZXESEAoIcGxhdGVOdW0YASACKAkSDQoFcmVzSUQYAiABKAUiIgoKUmVzR2V0UmVzcBIUCgxyZXNlcnZhdGlvbnMYASACKAkiTwoKUmVzRWRpdFJlcRINCgVyZXNJRBgBIAIoBRIQCghkYXRldGltZRgCIAEoCRIQCghkdXJhdGlvbhgDIAEoBRIOCgZjYW5jZWwYBCABKAgiQAoLUmVzRWRpdFJlc3ASDQoFcmVzSUQYASACKAUSDwoHc3VjY2VzcxgCIAIoCBIRCgllcnJvckNvZGUYAyABKAkyzgEKEENsaWVudF9JbnRlcmZhY2USPAoRZ2V0QXZhaWxhYmxlc3BvdHMSES5BdmFpbGFibGVzcG90UmVxGhIuQXZhaWxhYmxlc3BvdFJlc3AiABImCg9tYWtlUmVzZXJ2YXRpb24SBy5SZXNSZXEaCC5SZXNSZXNwIgASLAoPZ2V0UmVzZXJ2YXRpb25zEgouUmVzR2V0UmVxGgsuUmVzR2V0UmVzcCIAEiYKB2VkaXRSZXMSCy5SZXNFZGl0UmVxGgwuUmVzRWRpdFJlc3AiAA");

/**
 * Available spots request specifies which parking lot, time, and duration
 *
 * @generated from message AvailablespotReq
 */
export type AvailablespotReq = Message<"AvailablespotReq"> & {
  /**
   * @generated from field: required int32 lotID = 1;
   */
  lotID: number;

  /**
   * @generated from field: required string datetime = 2;
   */
  datetime: string;

  /**
   * @generated from field: required int32 duration = 3;
   */
  duration: number;
};

/**
 * Describes the message AvailablespotReq.
 * Use `create(AvailablespotReqSchema)` to create a new message.
 */
export const AvailablespotReqSchema: GenMessage<AvailablespotReq> = /*@__PURE__*/
  messageDesc(file_client_interface, 0);

/**
 * Available spot response returns list of available spots in that parking lot as JSON
 *
 * @generated from message AvailablespotResp
 */
export type AvailablespotResp = Message<"AvailablespotResp"> & {
  /**
   * @generated from field: required string availablespots = 1;
   */
  availablespots: string;
};

/**
 * Describes the message AvailablespotResp.
 * Use `create(AvailablespotRespSchema)` to create a new message.
 */
export const AvailablespotRespSchema: GenMessage<AvailablespotResp> = /*@__PURE__*/
  messageDesc(file_client_interface, 1);

/**
 * Reservation request specifies which parking lot and spot, userID, date and time, duration, and payment info
 *
 * @generated from message ResReq
 */
export type ResReq = Message<"ResReq"> & {
  /**
   * @generated from field: required int32 lotID = 1;
   */
  lotID: number;

  /**
   * @generated from field: required int32 spotID = 2;
   */
  spotID: number;

  /**
   * @generated from field: required string plateNum = 3;
   */
  plateNum: string;

  /**
   * @generated from field: required string paymentInfo = 4;
   */
  paymentInfo: string;

  /**
   * @generated from field: required string datetime = 5;
   */
  datetime: string;

  /**
   * @generated from field: required int32 duration = 6;
   */
  duration: number;

  /**
   * @generated from field: required float price = 7;
   */
  price: number;
};

/**
 * Describes the message ResReq.
 * Use `create(ResReqSchema)` to create a new message.
 */
export const ResReqSchema: GenMessage<ResReq> = /*@__PURE__*/
  messageDesc(file_client_interface, 2);

/**
 * Reservation response is success/fail
 *
 * @generated from message ResResp
 */
export type ResResp = Message<"ResResp"> & {
  /**
   * @generated from field: required bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: optional int32 resID = 2;
   */
  resID: number;

  /**
   * @generated from field: optional string errorCode = 3;
   */
  errorCode: string;
};

/**
 * Describes the message ResResp.
 * Use `create(ResRespSchema)` to create a new message.
 */
export const ResRespSchema: GenMessage<ResResp> = /*@__PURE__*/
  messageDesc(file_client_interface, 3);

/**
 * UserId to filter reservations from. If resID is provided, will return just that reservation's information
 *
 * @generated from message ResGetReq
 */
export type ResGetReq = Message<"ResGetReq"> & {
  /**
   * @generated from field: required string plateNum = 1;
   */
  plateNum: string;

  /**
   * @generated from field: optional int32 resID = 2;
   */
  resID: number;
};

/**
 * Describes the message ResGetReq.
 * Use `create(ResGetReqSchema)` to create a new message.
 */
export const ResGetReqSchema: GenMessage<ResGetReq> = /*@__PURE__*/
  messageDesc(file_client_interface, 4);

/**
 * Returns JSON formatted string
 *
 * @generated from message ResGetResp
 */
export type ResGetResp = Message<"ResGetResp"> & {
  /**
   * @generated from field: required string reservations = 1;
   */
  reservations: string;
};

/**
 * Describes the message ResGetResp.
 * Use `create(ResGetRespSchema)` to create a new message.
 */
export const ResGetRespSchema: GenMessage<ResGetResp> = /*@__PURE__*/
  messageDesc(file_client_interface, 5);

/**
 * @generated from message ResEditReq
 */
export type ResEditReq = Message<"ResEditReq"> & {
  /**
   * @generated from field: required int32 resID = 1;
   */
  resID: number;

  /**
   * @generated from field: optional string datetime = 2;
   */
  datetime: string;

  /**
   * @generated from field: optional int32 duration = 3;
   */
  duration: number;

  /**
   * @generated from field: optional bool cancel = 4;
   */
  cancel: boolean;
};

/**
 * Describes the message ResEditReq.
 * Use `create(ResEditReqSchema)` to create a new message.
 */
export const ResEditReqSchema: GenMessage<ResEditReq> = /*@__PURE__*/
  messageDesc(file_client_interface, 6);

/**
 * @generated from message ResEditResp
 */
export type ResEditResp = Message<"ResEditResp"> & {
  /**
   * @generated from field: required int32 resID = 1;
   */
  resID: number;

  /**
   * @generated from field: required bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: optional string errorCode = 3;
   */
  errorCode: string;
};

/**
 * Describes the message ResEditResp.
 * Use `create(ResEditRespSchema)` to create a new message.
 */
export const ResEditRespSchema: GenMessage<ResEditResp> = /*@__PURE__*/
  messageDesc(file_client_interface, 7);

/**
 * @generated from service Client_Interface
 */
export const Client_Interface: GenService<{
  /**
   * Client requests a list of available parking spots along with prices
   *
   * @generated from rpc Client_Interface.getAvailablespots
   */
  getAvailablespots: {
    methodKind: "unary";
    input: typeof AvailablespotReqSchema;
    output: typeof AvailablespotRespSchema;
  },
  /**
   * Client makes a reservation for a specific parking spot in a specific lot
   *
   * @generated from rpc Client_Interface.makeReservation
   */
  makeReservation: {
    methodKind: "unary";
    input: typeof ResReqSchema;
    output: typeof ResRespSchema;
  },
  /**
   * gets reservations made by a certain client.
   *
   * @generated from rpc Client_Interface.getReservations
   */
  getReservations: {
    methodKind: "unary";
    input: typeof ResGetReqSchema;
    output: typeof ResGetRespSchema;
  },
  /**
   * edits a reservation in the database
   *
   * @generated from rpc Client_Interface.editRes
   */
  editRes: {
    methodKind: "unary";
    input: typeof ResEditReqSchema;
    output: typeof ResEditRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_client_interface, 0);

