// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file database_interface.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file database_interface.proto.
 */
export const file_database_interface: GenFile = /*@__PURE__*/
  fileDesc("ChhkYXRhYmFzZV9pbnRlcmZhY2UucHJvdG8iRgoRQXZhaWxhYmxlU3BvdHNSZXESDQoFbG90SUQYASACKAUSEAoIZGF0ZXRpbWUYAiACKAkSEAoIZHVyYXRpb24YAyACKAUiLAoSQXZhaWxhYmxlU3BvdHNSZXNwEhYKDmF2YWlsYWJsZVNwb3RzGAEgAigJIoIBCgxVcGRhdGVSZXNSZXESDQoFcmVzSUQYASABKAUSDQoFbG90SUQYAiABKAUSDgoGc3BvdElEGAMgASgFEhAKCHBsYXRlTnVtGAQgASgJEhAKCGRhdGV0aW1lGAUgASgJEhAKCGR1cmF0aW9uGAYgASgFEg4KBmRlbGV0ZRgHIAEoCCJCCg1VcGRhdGVSZXNSZXNwEg8KB3N1Y2Nlc3MYASACKAgSDQoFcmVzSUQYAiACKAUSEQoJZXJyb3JDb2RlGAMgASgJImYKDlRyYW5zQ3JlYXRlUmVxEg0KBXJlc0lEGAEgAigFEhAKCHBsYXRlTnVtGAIgAigJEhUKDXBheW1lbnRNZXRob2QYAyACKAkSCwoDdmFsGAUgAigCEg8KB3N1Y2Nlc3MYBiACKAgiRgoPVHJhbnNDcmVhdGVSZXNwEg8KB3RyYW5zSUQYASACKAUSDwoHc3VjY2VzcxgCIAIoCBIRCgllcnJvckNvZGUYAyABKAkiLgoLVHJhbnNHZXRSZXESEAoIcGxhdGVOdW0YASABKAkSDQoFcmVzSUQYAiABKAUiJAoMVHJhbnNHZXRSZXNwEhQKDHRyYW5zYWN0aW9ucxgBIAIoCSIwCg1zcG90VXBkYXRlUmVxEg0KBWlvdElEGAEgAigFEhAKCG9jY3VwaWVkGAMgAigIIiEKDnNwb3RVcGRhdGVSZXNwEg8KB3N1Y2Nlc3MYASACKAgiLAoJR2V0UmVzUmVxEhAKCHBsYXRlTnVtGAEgAigJEg0KBXJlc0lEGAIgASgFIiIKCkdldFJlc1Jlc3ASFAoMcmVzZXJ2YXRpb25zGAEgAigJMt8CChJEYXRhYmFzZV9JbnRlcmZhY2USPgoRZ2V0QXZhaWxhYmxlU3BvdHMSEi5BdmFpbGFibGVTcG90c1JlcRoTLkF2YWlsYWJsZVNwb3RzUmVzcCIAEjUKEnVwZGF0ZVJlc2VydmF0aW9ucxINLlVwZGF0ZVJlc1JlcRoOLlVwZGF0ZVJlc1Jlc3AiABIsCg9nZXRSZXNlcnZhdGlvbnMSCi5HZXRSZXNSZXEaCy5HZXRSZXNSZXNwIgASOAoRY3JlYXRlVHJhbnNhY3Rpb24SDy5UcmFuc0NyZWF0ZVJlcRoQLlRyYW5zQ3JlYXRlUmVzcCIAEjAKD2dldFRyYW5zYWN0aW9ucxIMLlRyYW5zR2V0UmVxGg0uVHJhbnNHZXRSZXNwIgASOAoTdXBkYXRlU3BvdE9jY3VwYW5jeRIOLnNwb3RVcGRhdGVSZXEaDy5zcG90VXBkYXRlUmVzcCIA");

/**
 * Specifies which parking lot
 *
 * @generated from message AvailableSpotsReq
 */
export type AvailableSpotsReq = Message<"AvailableSpotsReq"> & {
  /**
   * @generated from field: required int32 lotID = 1;
   */
  lotID: number;

  /**
   * @generated from field: required string datetime = 2;
   */
  datetime: string;

  /**
   * @generated from field: required int32 duration = 3;
   */
  duration: number;
};

/**
 * Describes the message AvailableSpotsReq.
 * Use `create(AvailableSpotsReqSchema)` to create a new message.
 */
export const AvailableSpotsReqSchema: GenMessage<AvailableSpotsReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 0);

/**
 * Returns list of parking spots in JSON format
 *
 * @generated from message AvailableSpotsResp
 */
export type AvailableSpotsResp = Message<"AvailableSpotsResp"> & {
  /**
   * @generated from field: required string availableSpots = 1;
   */
  availableSpots: string;
};

/**
 * Describes the message AvailableSpotsResp.
 * Use `create(AvailableSpotsRespSchema)` to create a new message.
 */
export const AvailableSpotsRespSchema: GenMessage<AvailableSpotsResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 1);

/**
 * Request specifies reservation to be added/changed
 *
 * @generated from message UpdateResReq
 */
export type UpdateResReq = Message<"UpdateResReq"> & {
  /**
   * @generated from field: optional int32 resID = 1;
   */
  resID: number;

  /**
   * @generated from field: optional int32 lotID = 2;
   */
  lotID: number;

  /**
   * @generated from field: optional int32 spotID = 3;
   */
  spotID: number;

  /**
   * @generated from field: optional string plateNum = 4;
   */
  plateNum: string;

  /**
   * @generated from field: optional string datetime = 5;
   */
  datetime: string;

  /**
   * @generated from field: optional int32 duration = 6;
   */
  duration: number;

  /**
   * @generated from field: optional bool delete = 7;
   */
  delete: boolean;
};

/**
 * Describes the message UpdateResReq.
 * Use `create(UpdateResReqSchema)` to create a new message.
 */
export const UpdateResReqSchema: GenMessage<UpdateResReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 2);

/**
 * Response returns success/fail and resID
 *
 * @generated from message UpdateResResp
 */
export type UpdateResResp = Message<"UpdateResResp"> & {
  /**
   * @generated from field: required bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: required int32 resID = 2;
   */
  resID: number;

  /**
   * @generated from field: optional string errorCode = 3;
   */
  errorCode: string;
};

/**
 * Describes the message UpdateResResp.
 * Use `create(UpdateResRespSchema)` to create a new message.
 */
export const UpdateResRespSchema: GenMessage<UpdateResResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 3);

/**
 * Transaction create request consists of related reservation ID, user ID, payment method, and success/fail
 *
 * @generated from message TransCreateReq
 */
export type TransCreateReq = Message<"TransCreateReq"> & {
  /**
   * @generated from field: required int32 resID = 1;
   */
  resID: number;

  /**
   * @generated from field: required string plateNum = 2;
   */
  plateNum: string;

  /**
   * @generated from field: required string paymentMethod = 3;
   */
  paymentMethod: string;

  /**
   * @generated from field: required float val = 5;
   */
  val: number;

  /**
   * @generated from field: required bool success = 6;
   */
  success: boolean;
};

/**
 * Describes the message TransCreateReq.
 * Use `create(TransCreateReqSchema)` to create a new message.
 */
export const TransCreateReqSchema: GenMessage<TransCreateReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 4);

/**
 * Transaction create response consists of success/fail and transaction ID
 *
 * @generated from message TransCreateResp
 */
export type TransCreateResp = Message<"TransCreateResp"> & {
  /**
   * @generated from field: required int32 transID = 1;
   */
  transID: number;

  /**
   * @generated from field: required bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: optional string errorCode = 3;
   */
  errorCode: string;
};

/**
 * Describes the message TransCreateResp.
 * Use `create(TransCreateRespSchema)` to create a new message.
 */
export const TransCreateRespSchema: GenMessage<TransCreateResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 5);

/**
 * Transaction get request contains uID or resID, or none to get all transactions made
 *
 * @generated from message TransGetReq
 */
export type TransGetReq = Message<"TransGetReq"> & {
  /**
   * @generated from field: optional string plateNum = 1;
   */
  plateNum: string;

  /**
   * @generated from field: optional int32 resID = 2;
   */
  resID: number;
};

/**
 * Describes the message TransGetReq.
 * Use `create(TransGetReqSchema)` to create a new message.
 */
export const TransGetReqSchema: GenMessage<TransGetReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 6);

/**
 * returned list of transactions is in JSON formatted string
 *
 * @generated from message TransGetResp
 */
export type TransGetResp = Message<"TransGetResp"> & {
  /**
   * @generated from field: required string transactions = 1;
   */
  transactions: string;
};

/**
 * Describes the message TransGetResp.
 * Use `create(TransGetRespSchema)` to create a new message.
 */
export const TransGetRespSchema: GenMessage<TransGetResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 7);

/**
 * updates spot's occupancy state
 *
 * @generated from message spotUpdateReq
 */
export type spotUpdateReq = Message<"spotUpdateReq"> & {
  /**
   * @generated from field: required int32 iotID = 1;
   */
  iotID: number;

  /**
   * @generated from field: required bool occupied = 3;
   */
  occupied: boolean;
};

/**
 * Describes the message spotUpdateReq.
 * Use `create(spotUpdateReqSchema)` to create a new message.
 */
export const spotUpdateReqSchema: GenMessage<spotUpdateReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 8);

/**
 * returns success or fail
 *
 * @generated from message spotUpdateResp
 */
export type spotUpdateResp = Message<"spotUpdateResp"> & {
  /**
   * @generated from field: required bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message spotUpdateResp.
 * Use `create(spotUpdateRespSchema)` to create a new message.
 */
export const spotUpdateRespSchema: GenMessage<spotUpdateResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 9);

/**
 * request contains plate number and resID (optional)
 *
 * @generated from message GetResReq
 */
export type GetResReq = Message<"GetResReq"> & {
  /**
   * @generated from field: required string plateNum = 1;
   */
  plateNum: string;

  /**
   * @generated from field: optional int32 resID = 2;
   */
  resID: number;
};

/**
 * Describes the message GetResReq.
 * Use `create(GetResReqSchema)` to create a new message.
 */
export const GetResReqSchema: GenMessage<GetResReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 10);

/**
 * returns reservations as JSON
 *
 * @generated from message GetResResp
 */
export type GetResResp = Message<"GetResResp"> & {
  /**
   * @generated from field: required string reservations = 1;
   */
  reservations: string;
};

/**
 * Describes the message GetResResp.
 * Use `create(GetResRespSchema)` to create a new message.
 */
export const GetResRespSchema: GenMessage<GetResResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 11);

/**
 * @generated from service Database_Interface
 */
export const Database_Interface: GenService<{
  /**
   * Requests list of available spots
   *
   * @generated from rpc Database_Interface.getAvailableSpots
   */
  getAvailableSpots: {
    methodKind: "unary";
    input: typeof AvailableSpotsReqSchema;
    output: typeof AvailableSpotsRespSchema;
  },
  /**
   * Updates list of reservations
   *
   * @generated from rpc Database_Interface.updateReservations
   */
  updateReservations: {
    methodKind: "unary";
    input: typeof UpdateResReqSchema;
    output: typeof UpdateResRespSchema;
  },
  /**
   * gets a list of reservations made by the user
   *
   * @generated from rpc Database_Interface.getReservations
   */
  getReservations: {
    methodKind: "unary";
    input: typeof GetResReqSchema;
    output: typeof GetResRespSchema;
  },
  /**
   * creates a new transaction, used by transaction handler
   *
   * @generated from rpc Database_Interface.createTransaction
   */
  createTransaction: {
    methodKind: "unary";
    input: typeof TransCreateReqSchema;
    output: typeof TransCreateRespSchema;
  },
  /**
   * Returns a list of transactions for the specified reservation/user
   *
   * @generated from rpc Database_Interface.getTransactions
   */
  getTransactions: {
    methodKind: "unary";
    input: typeof TransGetReqSchema;
    output: typeof TransGetRespSchema;
  },
  /**
   * Updates the occupancy of a spot given spotID and lotID
   *
   * @generated from rpc Database_Interface.updateSpotOccupancy
   */
  updateSpotOccupancy: {
    methodKind: "unary";
    input: typeof spotUpdateReqSchema;
    output: typeof spotUpdateRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_database_interface, 0);

