// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file database_interface.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file database_interface.proto.
 */
export const file_database_interface: GenFile = /*@__PURE__*/
  fileDesc("ChhkYXRhYmFzZV9pbnRlcmZhY2UucHJvdG8iRgoRQXZhaWxhYmxlU3BvdHNSZXESDQoFbG90SUQYASACKAkSEAoIZGF0ZXRpbWUYAiACKAkSEAoIZHVyYXRpb24YAyACKAUiLAoSQXZhaWxhYmxlU3BvdHNSZXNwEhYKDmF2YWlsYWJsZVNwb3RzGAEgAigJInIKDFVwZGF0ZVJlc1JlcRINCgVyZXNJRBgBIAEoCRINCgVsb3RJRBgCIAEoCRIOCgZzcG90SUQYAyABKAkSEAoIcGxhdGVOdW0YBCABKAkSEAoIZGF0ZXRpbWUYBSABKAkSEAoIZHVyYXRpb24YBiABKAkiQgoNVXBkYXRlUmVzUmVzcBIPCgdzdWNjZXNzGAEgAigIEg0KBXJlc0lEGAIgAigIEhEKCWVycm9yQ29kZRgDIAEoCSJmCg5UcmFuc0NyZWF0ZVJlcRINCgVyZXNJRBgBIAIoCRIQCghwbGF0ZU51bRgCIAIoCRIVCg1wYXltZW50TWV0aG9kGAMgAigJEgsKA3ZhbBgFIAIoAhIPCgdzdWNjZXNzGAYgAigIIkYKD1RyYW5zQ3JlYXRlUmVzcBIPCgd0cmFuc0lEGAEgAigJEg8KB3N1Y2Nlc3MYAiACKAgSEQoJZXJyb3JDb2RlGAMgASgJIi4KC1RyYW5zR2V0UmVxEhAKCHBsYXRlTnVtGAEgASgJEg0KBXJlc0lEGAIgASgJIiQKDFRyYW5zR2V0UmVzcBIUCgx0cmFuc2FjdGlvbnMYASACKAky9wEKEkRhdGFiYXNlX0ludGVyZmFjZRI+ChFnZXRBdmFpbGFibGVTcG90cxISLkF2YWlsYWJsZVNwb3RzUmVxGhMuQXZhaWxhYmxlU3BvdHNSZXNwIgASNQoSdXBkYXRlUmVzZXJ2YXRpb25zEg0uVXBkYXRlUmVzUmVxGg4uVXBkYXRlUmVzUmVzcCIAEjgKEWNyZWF0ZVRyYW5zYWN0aW9uEg8uVHJhbnNDcmVhdGVSZXEaEC5UcmFuc0NyZWF0ZVJlc3AiABIwCg9nZXRUcmFuc2FjdGlvbnMSDC5UcmFuc0dldFJlcRoNLlRyYW5zR2V0UmVzcCIA");

/**
 * Specifies which parking lot
 *
 * @generated from message AvailableSpotsReq
 */
export type AvailableSpotsReq = Message<"AvailableSpotsReq"> & {
  /**
   * @generated from field: required string lotID = 1;
   */
  lotID: string;

  /**
   * @generated from field: required string datetime = 2;
   */
  datetime: string;

  /**
   * @generated from field: required int32 duration = 3;
   */
  duration: number;
};

/**
 * Describes the message AvailableSpotsReq.
 * Use `create(AvailableSpotsReqSchema)` to create a new message.
 */
export const AvailableSpotsReqSchema: GenMessage<AvailableSpotsReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 0);

/**
 * Returns list of parking spots in JSON format
 *
 * @generated from message AvailableSpotsResp
 */
export type AvailableSpotsResp = Message<"AvailableSpotsResp"> & {
  /**
   * @generated from field: required string availableSpots = 1;
   */
  availableSpots: string;
};

/**
 * Describes the message AvailableSpotsResp.
 * Use `create(AvailableSpotsRespSchema)` to create a new message.
 */
export const AvailableSpotsRespSchema: GenMessage<AvailableSpotsResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 1);

/**
 * Request specifies reservation to be added/changed
 *
 * @generated from message UpdateResReq
 */
export type UpdateResReq = Message<"UpdateResReq"> & {
  /**
   * @generated from field: optional string resID = 1;
   */
  resID: string;

  /**
   * @generated from field: optional string lotID = 2;
   */
  lotID: string;

  /**
   * @generated from field: optional string spotID = 3;
   */
  spotID: string;

  /**
   * @generated from field: optional string plateNum = 4;
   */
  plateNum: string;

  /**
   * @generated from field: optional string datetime = 5;
   */
  datetime: string;

  /**
   * @generated from field: optional string duration = 6;
   */
  duration: string;
};

/**
 * Describes the message UpdateResReq.
 * Use `create(UpdateResReqSchema)` to create a new message.
 */
export const UpdateResReqSchema: GenMessage<UpdateResReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 2);

/**
 * Response returns success/fail and resID
 *
 * @generated from message UpdateResResp
 */
export type UpdateResResp = Message<"UpdateResResp"> & {
  /**
   * @generated from field: required bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: required bool resID = 2;
   */
  resID: boolean;

  /**
   * @generated from field: optional string errorCode = 3;
   */
  errorCode: string;
};

/**
 * Describes the message UpdateResResp.
 * Use `create(UpdateResRespSchema)` to create a new message.
 */
export const UpdateResRespSchema: GenMessage<UpdateResResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 3);

/**
 * Transaction create request consists of related reservation ID, user ID, payment method, and success/fail
 *
 * @generated from message TransCreateReq
 */
export type TransCreateReq = Message<"TransCreateReq"> & {
  /**
   * @generated from field: required string resID = 1;
   */
  resID: string;

  /**
   * @generated from field: required string plateNum = 2;
   */
  plateNum: string;

  /**
   * @generated from field: required string paymentMethod = 3;
   */
  paymentMethod: string;

  /**
   * @generated from field: required float val = 5;
   */
  val: number;

  /**
   * @generated from field: required bool success = 6;
   */
  success: boolean;
};

/**
 * Describes the message TransCreateReq.
 * Use `create(TransCreateReqSchema)` to create a new message.
 */
export const TransCreateReqSchema: GenMessage<TransCreateReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 4);

/**
 * Transaction create response consists of success/fail and transaction ID
 *
 * @generated from message TransCreateResp
 */
export type TransCreateResp = Message<"TransCreateResp"> & {
  /**
   * @generated from field: required string transID = 1;
   */
  transID: string;

  /**
   * @generated from field: required bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: optional string errorCode = 3;
   */
  errorCode: string;
};

/**
 * Describes the message TransCreateResp.
 * Use `create(TransCreateRespSchema)` to create a new message.
 */
export const TransCreateRespSchema: GenMessage<TransCreateResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 5);

/**
 * Transaction get request contains uID or resID, or none to get all transactions made
 *
 * @generated from message TransGetReq
 */
export type TransGetReq = Message<"TransGetReq"> & {
  /**
   * @generated from field: optional string plateNum = 1;
   */
  plateNum: string;

  /**
   * @generated from field: optional string resID = 2;
   */
  resID: string;
};

/**
 * Describes the message TransGetReq.
 * Use `create(TransGetReqSchema)` to create a new message.
 */
export const TransGetReqSchema: GenMessage<TransGetReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 6);

/**
 * returned list of transactions is in JSON formatted string
 *
 * @generated from message TransGetResp
 */
export type TransGetResp = Message<"TransGetResp"> & {
  /**
   * @generated from field: required string transactions = 1;
   */
  transactions: string;
};

/**
 * Describes the message TransGetResp.
 * Use `create(TransGetRespSchema)` to create a new message.
 */
export const TransGetRespSchema: GenMessage<TransGetResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 7);

/**
 * @generated from service Database_Interface
 */
export const Database_Interface: GenService<{
  /**
   * Requests list of available spots
   *
   * @generated from rpc Database_Interface.getAvailableSpots
   */
  getAvailableSpots: {
    methodKind: "unary";
    input: typeof AvailableSpotsReqSchema;
    output: typeof AvailableSpotsRespSchema;
  },
  /**
   * Updates list of reservations
   *
   * @generated from rpc Database_Interface.updateReservations
   */
  updateReservations: {
    methodKind: "unary";
    input: typeof UpdateResReqSchema;
    output: typeof UpdateResRespSchema;
  },
  /**
   * creates a new transaction, used by transaction handler
   *
   * @generated from rpc Database_Interface.createTransaction
   */
  createTransaction: {
    methodKind: "unary";
    input: typeof TransCreateReqSchema;
    output: typeof TransCreateRespSchema;
  },
  /**
   * Returns a list of transactions for the specified reservation/user
   *
   * @generated from rpc Database_Interface.getTransactions
   */
  getTransactions: {
    methodKind: "unary";
    input: typeof TransGetReqSchema;
    output: typeof TransGetRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_database_interface, 0);

