/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v7.34.1
// source: database_interface.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as database_interface_pb from './database_interface_pb'; // proto import: "database_interface.proto"


export class Database_InterfaceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorgetAvailableSpots = new grpcWeb.MethodDescriptor(
    '/Database_Interface/getAvailableSpots',
    grpcWeb.MethodType.UNARY,
    database_interface_pb.AvailableSpotsReq,
    database_interface_pb.AvailableSpotsResp,
    (request: database_interface_pb.AvailableSpotsReq) => {
      return request.serializeBinary();
    },
    database_interface_pb.AvailableSpotsResp.deserializeBinary
  );

  getAvailableSpots(
    request: database_interface_pb.AvailableSpotsReq,
    metadata?: grpcWeb.Metadata | null): Promise<database_interface_pb.AvailableSpotsResp>;

  getAvailableSpots(
    request: database_interface_pb.AvailableSpotsReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: database_interface_pb.AvailableSpotsResp) => void): grpcWeb.ClientReadableStream<database_interface_pb.AvailableSpotsResp>;

  getAvailableSpots(
    request: database_interface_pb.AvailableSpotsReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: database_interface_pb.AvailableSpotsResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Database_Interface/getAvailableSpots',
        request,
        metadata || {},
        this.methodDescriptorgetAvailableSpots,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Database_Interface/getAvailableSpots',
    request,
    metadata || {},
    this.methodDescriptorgetAvailableSpots);
  }

  methodDescriptorupdateReservations = new grpcWeb.MethodDescriptor(
    '/Database_Interface/updateReservations',
    grpcWeb.MethodType.UNARY,
    database_interface_pb.UpdateResReq,
    database_interface_pb.UpdateResResp,
    (request: database_interface_pb.UpdateResReq) => {
      return request.serializeBinary();
    },
    database_interface_pb.UpdateResResp.deserializeBinary
  );

  updateReservations(
    request: database_interface_pb.UpdateResReq,
    metadata?: grpcWeb.Metadata | null): Promise<database_interface_pb.UpdateResResp>;

  updateReservations(
    request: database_interface_pb.UpdateResReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: database_interface_pb.UpdateResResp) => void): grpcWeb.ClientReadableStream<database_interface_pb.UpdateResResp>;

  updateReservations(
    request: database_interface_pb.UpdateResReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: database_interface_pb.UpdateResResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Database_Interface/updateReservations',
        request,
        metadata || {},
        this.methodDescriptorupdateReservations,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Database_Interface/updateReservations',
    request,
    metadata || {},
    this.methodDescriptorupdateReservations);
  }

  methodDescriptorcreateTransaction = new grpcWeb.MethodDescriptor(
    '/Database_Interface/createTransaction',
    grpcWeb.MethodType.UNARY,
    database_interface_pb.TransCreateReq,
    database_interface_pb.TransCreateResp,
    (request: database_interface_pb.TransCreateReq) => {
      return request.serializeBinary();
    },
    database_interface_pb.TransCreateResp.deserializeBinary
  );

  createTransaction(
    request: database_interface_pb.TransCreateReq,
    metadata?: grpcWeb.Metadata | null): Promise<database_interface_pb.TransCreateResp>;

  createTransaction(
    request: database_interface_pb.TransCreateReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: database_interface_pb.TransCreateResp) => void): grpcWeb.ClientReadableStream<database_interface_pb.TransCreateResp>;

  createTransaction(
    request: database_interface_pb.TransCreateReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: database_interface_pb.TransCreateResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Database_Interface/createTransaction',
        request,
        metadata || {},
        this.methodDescriptorcreateTransaction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Database_Interface/createTransaction',
    request,
    metadata || {},
    this.methodDescriptorcreateTransaction);
  }

  methodDescriptorgetTransactions = new grpcWeb.MethodDescriptor(
    '/Database_Interface/getTransactions',
    grpcWeb.MethodType.UNARY,
    database_interface_pb.TransGetReq,
    database_interface_pb.TransGetResp,
    (request: database_interface_pb.TransGetReq) => {
      return request.serializeBinary();
    },
    database_interface_pb.TransGetResp.deserializeBinary
  );

  getTransactions(
    request: database_interface_pb.TransGetReq,
    metadata?: grpcWeb.Metadata | null): Promise<database_interface_pb.TransGetResp>;

  getTransactions(
    request: database_interface_pb.TransGetReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: database_interface_pb.TransGetResp) => void): grpcWeb.ClientReadableStream<database_interface_pb.TransGetResp>;

  getTransactions(
    request: database_interface_pb.TransGetReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: database_interface_pb.TransGetResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Database_Interface/getTransactions',
        request,
        metadata || {},
        this.methodDescriptorgetTransactions,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Database_Interface/getTransactions',
    request,
    metadata || {},
    this.methodDescriptorgetTransactions);
  }

  methodDescriptorupdateUser = new grpcWeb.MethodDescriptor(
    '/Database_Interface/updateUser',
    grpcWeb.MethodType.UNARY,
    database_interface_pb.userUpdateReq,
    database_interface_pb.userUpdateResp,
    (request: database_interface_pb.userUpdateReq) => {
      return request.serializeBinary();
    },
    database_interface_pb.userUpdateResp.deserializeBinary
  );

  updateUser(
    request: database_interface_pb.userUpdateReq,
    metadata?: grpcWeb.Metadata | null): Promise<database_interface_pb.userUpdateResp>;

  updateUser(
    request: database_interface_pb.userUpdateReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: database_interface_pb.userUpdateResp) => void): grpcWeb.ClientReadableStream<database_interface_pb.userUpdateResp>;

  updateUser(
    request: database_interface_pb.userUpdateReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: database_interface_pb.userUpdateResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Database_Interface/updateUser',
        request,
        metadata || {},
        this.methodDescriptorupdateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Database_Interface/updateUser',
    request,
    metadata || {},
    this.methodDescriptorupdateUser);
  }

  methodDescriptorgetUser = new grpcWeb.MethodDescriptor(
    '/Database_Interface/getUser',
    grpcWeb.MethodType.UNARY,
    database_interface_pb.userGetReq,
    database_interface_pb.userGetResp,
    (request: database_interface_pb.userGetReq) => {
      return request.serializeBinary();
    },
    database_interface_pb.userGetResp.deserializeBinary
  );

  getUser(
    request: database_interface_pb.userGetReq,
    metadata?: grpcWeb.Metadata | null): Promise<database_interface_pb.userGetResp>;

  getUser(
    request: database_interface_pb.userGetReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: database_interface_pb.userGetResp) => void): grpcWeb.ClientReadableStream<database_interface_pb.userGetResp>;

  getUser(
    request: database_interface_pb.userGetReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: database_interface_pb.userGetResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Database_Interface/getUser',
        request,
        metadata || {},
        this.methodDescriptorgetUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Database_Interface/getUser',
    request,
    metadata || {},
    this.methodDescriptorgetUser);
  }

}

