// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file database_interface.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file database_interface.proto.
 */
export const file_database_interface: GenFile = /*@__PURE__*/
  fileDesc("ChhkYXRhYmFzZV9pbnRlcmZhY2UucHJvdG8iIgoRQXZhaWxhYmxlU3BvdHNSZXESDQoFbG90SUQYASACKAkiLAoSQXZhaWxhYmxlU3BvdHNSZXNwEhYKDmF2YWlsYWJsZVNwb3RzGAEgAigJIm0KDFVwZGF0ZVJlc1JlcRINCgVyZXNJRBgBIAEoCRINCgVsb3RJRBgCIAIoCRIOCgZzcG90SUQYAyACKAkSCwoDdUlEGAQgAigJEhAKCGRhdGV0aW1lGAUgAigJEhAKCGR1cmF0aW9uGAYgAigJIkIKDVVwZGF0ZVJlc1Jlc3ASDwoHc3VjY2VzcxgBIAIoCBINCgVyZXNJRBgCIAIoCBIRCgllcnJvckNvZGUYAyABKAkiYQoOVHJhbnNDcmVhdGVSZXESDQoFcmVzSUQYASACKAkSCwoDdUlEGAIgAigJEhUKDXBheW1lbnRNZXRob2QYAyACKAkSCwoDdmFsGAUgAigJEg8KB3N1Y2Nlc3MYBiACKAgiRgoPVHJhbnNDcmVhdGVSZXNwEg8KB3RyYW5zSUQYASACKAkSDwoHc3VjY2VzcxgCIAIoCBIRCgllcnJvckNvZGUYAyABKAkiKQoLVHJhbnNHZXRSZXESCwoDdUlEGAEgASgJEg0KBXJlc0lEGAIgASgJIiQKDFRyYW5zR2V0UmVzcBIUCgx0cmFuc2FjdGlvbnMYASACKAkiTwoNdXNlclVwZGF0ZVJlcRILCgN1SUQYASABKAkSEAoIdXNlcm5hbWUYAiABKAkSEAoIcGFzc3dvcmQYAyABKAkSDQoFZW1haWwYBCABKAkiNAoOdXNlclVwZGF0ZVJlc3ASDwoHc3VjY2VzcxgBIAIoCBIRCgllcnJvckNvZGUYAiABKAkiLQoKdXNlckdldFJlcRIQCgh1c2VybmFtZRgBIAEoCRINCgVlbWFpbBgCIAEoCSIfCgt1c2VyR2V0UmVzcBIQCgh1c2VyRGF0YRgBIAIoCTLQAgoSRGF0YWJhc2VfSW50ZXJmYWNlEj4KEWdldEF2YWlsYWJsZVNwb3RzEhIuQXZhaWxhYmxlU3BvdHNSZXEaEy5BdmFpbGFibGVTcG90c1Jlc3AiABI1ChJ1cGRhdGVSZXNlcnZhdGlvbnMSDS5VcGRhdGVSZXNSZXEaDi5VcGRhdGVSZXNSZXNwIgASOAoRY3JlYXRlVHJhbnNhY3Rpb24SDy5UcmFuc0NyZWF0ZVJlcRoQLlRyYW5zQ3JlYXRlUmVzcCIAEjAKD2dldFRyYW5zYWN0aW9ucxIMLlRyYW5zR2V0UmVxGg0uVHJhbnNHZXRSZXNwIgASLwoKdXBkYXRlVXNlchIOLnVzZXJVcGRhdGVSZXEaDy51c2VyVXBkYXRlUmVzcCIAEiYKB2dldFVzZXISCy51c2VyR2V0UmVxGgwudXNlckdldFJlc3AiAA");

/**
 * Specifies which parking lot
 *
 * @generated from message AvailableSpotsReq
 */
export type AvailableSpotsReq = Message<"AvailableSpotsReq"> & {
  /**
   * @generated from field: required string lotID = 1;
   */
  lotID: string;
};

/**
 * Describes the message AvailableSpotsReq.
 * Use `create(AvailableSpotsReqSchema)` to create a new message.
 */
export const AvailableSpotsReqSchema: GenMessage<AvailableSpotsReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 0);

/**
 * Returns list of parking spots in JSON format
 *
 * @generated from message AvailableSpotsResp
 */
export type AvailableSpotsResp = Message<"AvailableSpotsResp"> & {
  /**
   * @generated from field: required string availableSpots = 1;
   */
  availableSpots: string;
};

/**
 * Describes the message AvailableSpotsResp.
 * Use `create(AvailableSpotsRespSchema)` to create a new message.
 */
export const AvailableSpotsRespSchema: GenMessage<AvailableSpotsResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 1);

/**
 * Request specifies reservation to be added/changed
 *
 * @generated from message UpdateResReq
 */
export type UpdateResReq = Message<"UpdateResReq"> & {
  /**
   * @generated from field: optional string resID = 1;
   */
  resID: string;

  /**
   * @generated from field: required string lotID = 2;
   */
  lotID: string;

  /**
   * @generated from field: required string spotID = 3;
   */
  spotID: string;

  /**
   * @generated from field: required string uID = 4;
   */
  uID: string;

  /**
   * @generated from field: required string datetime = 5;
   */
  datetime: string;

  /**
   * @generated from field: required string duration = 6;
   */
  duration: string;
};

/**
 * Describes the message UpdateResReq.
 * Use `create(UpdateResReqSchema)` to create a new message.
 */
export const UpdateResReqSchema: GenMessage<UpdateResReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 2);

/**
 * Response returns success/fail and resID
 *
 * @generated from message UpdateResResp
 */
export type UpdateResResp = Message<"UpdateResResp"> & {
  /**
   * @generated from field: required bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: required bool resID = 2;
   */
  resID: boolean;

  /**
   * @generated from field: optional string errorCode = 3;
   */
  errorCode: string;
};

/**
 * Describes the message UpdateResResp.
 * Use `create(UpdateResRespSchema)` to create a new message.
 */
export const UpdateResRespSchema: GenMessage<UpdateResResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 3);

/**
 * Transaction create request consists of related reservation ID, user ID, payment method, and success/fail
 *
 * @generated from message TransCreateReq
 */
export type TransCreateReq = Message<"TransCreateReq"> & {
  /**
   * @generated from field: required string resID = 1;
   */
  resID: string;

  /**
   * @generated from field: required string uID = 2;
   */
  uID: string;

  /**
   * @generated from field: required string paymentMethod = 3;
   */
  paymentMethod: string;

  /**
   * @generated from field: required string val = 5;
   */
  val: string;

  /**
   * @generated from field: required bool success = 6;
   */
  success: boolean;
};

/**
 * Describes the message TransCreateReq.
 * Use `create(TransCreateReqSchema)` to create a new message.
 */
export const TransCreateReqSchema: GenMessage<TransCreateReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 4);

/**
 * Transaction create response consists of success/fail and transaction ID
 *
 * @generated from message TransCreateResp
 */
export type TransCreateResp = Message<"TransCreateResp"> & {
  /**
   * @generated from field: required string transID = 1;
   */
  transID: string;

  /**
   * @generated from field: required bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: optional string errorCode = 3;
   */
  errorCode: string;
};

/**
 * Describes the message TransCreateResp.
 * Use `create(TransCreateRespSchema)` to create a new message.
 */
export const TransCreateRespSchema: GenMessage<TransCreateResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 5);

/**
 * Transaction get request contains uID or resID, or none to get all transactions made
 *
 * @generated from message TransGetReq
 */
export type TransGetReq = Message<"TransGetReq"> & {
  /**
   * @generated from field: optional string uID = 1;
   */
  uID: string;

  /**
   * @generated from field: optional string resID = 2;
   */
  resID: string;
};

/**
 * Describes the message TransGetReq.
 * Use `create(TransGetReqSchema)` to create a new message.
 */
export const TransGetReqSchema: GenMessage<TransGetReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 6);

/**
 * returned list of transactions is in JSON formatted string
 *
 * @generated from message TransGetResp
 */
export type TransGetResp = Message<"TransGetResp"> & {
  /**
   * @generated from field: required string transactions = 1;
   */
  transactions: string;
};

/**
 * Describes the message TransGetResp.
 * Use `create(TransGetRespSchema)` to create a new message.
 */
export const TransGetRespSchema: GenMessage<TransGetResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 7);

/**
 * contains user info to be updated
 *
 * @generated from message userUpdateReq
 */
export type userUpdateReq = Message<"userUpdateReq"> & {
  /**
   * @generated from field: optional string uID = 1;
   */
  uID: string;

  /**
   * @generated from field: optional string username = 2;
   */
  username: string;

  /**
   * @generated from field: optional string password = 3;
   */
  password: string;

  /**
   * @generated from field: optional string email = 4;
   */
  email: string;
};

/**
 * Describes the message userUpdateReq.
 * Use `create(userUpdateReqSchema)` to create a new message.
 */
export const userUpdateReqSchema: GenMessage<userUpdateReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 8);

/**
 * response is success/fail
 *
 * @generated from message userUpdateResp
 */
export type userUpdateResp = Message<"userUpdateResp"> & {
  /**
   * @generated from field: required bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: optional string errorCode = 2;
   */
  errorCode: string;
};

/**
 * Describes the message userUpdateResp.
 * Use `create(userUpdateRespSchema)` to create a new message.
 */
export const userUpdateRespSchema: GenMessage<userUpdateResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 9);

/**
 * get request uses username or email
 *
 * @generated from message userGetReq
 */
export type userGetReq = Message<"userGetReq"> & {
  /**
   * @generated from field: optional string username = 1;
   */
  username: string;

  /**
   * @generated from field: optional string email = 2;
   */
  email: string;
};

/**
 * Describes the message userGetReq.
 * Use `create(userGetReqSchema)` to create a new message.
 */
export const userGetReqSchema: GenMessage<userGetReq> = /*@__PURE__*/
  messageDesc(file_database_interface, 10);

/**
 * returns user info as JSON
 *
 * @generated from message userGetResp
 */
export type userGetResp = Message<"userGetResp"> & {
  /**
   * @generated from field: required string userData = 1;
   */
  userData: string;
};

/**
 * Describes the message userGetResp.
 * Use `create(userGetRespSchema)` to create a new message.
 */
export const userGetRespSchema: GenMessage<userGetResp> = /*@__PURE__*/
  messageDesc(file_database_interface, 11);

/**
 * @generated from service Database_Interface
 */
export const Database_Interface: GenService<{
  /**
   * Requests list of available spots
   *
   * @generated from rpc Database_Interface.getAvailableSpots
   */
  getAvailableSpots: {
    methodKind: "unary";
    input: typeof AvailableSpotsReqSchema;
    output: typeof AvailableSpotsRespSchema;
  },
  /**
   * Updates list of reservations
   *
   * @generated from rpc Database_Interface.updateReservations
   */
  updateReservations: {
    methodKind: "unary";
    input: typeof UpdateResReqSchema;
    output: typeof UpdateResRespSchema;
  },
  /**
   * creates a new transaction, used by transaction handler
   *
   * @generated from rpc Database_Interface.createTransaction
   */
  createTransaction: {
    methodKind: "unary";
    input: typeof TransCreateReqSchema;
    output: typeof TransCreateRespSchema;
  },
  /**
   * Returns a list of transactions for the specified reservation/user
   *
   * @generated from rpc Database_Interface.getTransactions
   */
  getTransactions: {
    methodKind: "unary";
    input: typeof TransGetReqSchema;
    output: typeof TransGetRespSchema;
  },
  /**
   * Updates user info (or creates a new one)
   *
   * @generated from rpc Database_Interface.updateUser
   */
  updateUser: {
    methodKind: "unary";
    input: typeof userUpdateReqSchema;
    output: typeof userUpdateRespSchema;
  },
  /**
   * Returns requested user info
   *
   * @generated from rpc Database_Interface.getUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof userGetReqSchema;
    output: typeof userGetRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_database_interface, 0);

