// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file pricing_calculator.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file pricing_calculator.proto.
 */
export const file_pricing_calculator: GenFile = /*@__PURE__*/
  fileDesc("ChhwcmljaW5nX2NhbGN1bGF0b3IucHJvdG8iTAoIUHJpY2VSZXESDQoFbG90SUQYASACKAkSDQoFc3BvdHMYAiADKAkSEAoIZGF0ZXRpbWUYAyACKAkSEAoIZHVyYXRpb24YBCACKAUiGwoJUHJpY2VSZXNwEg4KBnByaWNlcxgBIAIoCTI5ChJQcmljaW5nX0NhbGN1bGF0b3ISIwoIZ2V0UHJpY2USCS5QcmljZVJlcRoKLlByaWNlUmVzcCIA");

/**
 * Price Request specifies which lot and available spots. Spots is formatted as JSON, datetime is DD/MM/YYYY HH:MM, duration is in minutes
 *
 * @generated from message PriceReq
 */
export type PriceReq = Message<"PriceReq"> & {
  /**
   * @generated from field: required string lotID = 1;
   */
  lotID: string;

  /**
   * @generated from field: repeated string spots = 2;
   */
  spots: string[];

  /**
   * @generated from field: required string datetime = 3;
   */
  datetime: string;

  /**
   * @generated from field: required int32 duration = 4;
   */
  duration: number;
};

/**
 * Describes the message PriceReq.
 * Use `create(PriceReqSchema)` to create a new message.
 */
export const PriceReqSchema: GenMessage<PriceReq> = /*@__PURE__*/
  messageDesc(file_pricing_calculator, 0);

/**
 * Price Response returns the price for each available spot in the lot as a JSON
 *
 * @generated from message PriceResp
 */
export type PriceResp = Message<"PriceResp"> & {
  /**
   * @generated from field: required string prices = 1;
   */
  prices: string;
};

/**
 * Describes the message PriceResp.
 * Use `create(PriceRespSchema)` to create a new message.
 */
export const PriceRespSchema: GenMessage<PriceResp> = /*@__PURE__*/
  messageDesc(file_pricing_calculator, 1);

/**
 * @generated from service Pricing_Calculator
 */
export const Pricing_Calculator: GenService<{
  /**
   * Client Interface requests a price for a spot
   *
   * @generated from rpc Pricing_Calculator.getPrice
   */
  getPrice: {
    methodKind: "unary";
    input: typeof PriceReqSchema;
    output: typeof PriceRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_pricing_calculator, 0);

