// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file pricing_calculator.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file pricing_calculator.proto.
 */
export const file_pricing_calculator: GenFile = /*@__PURE__*/
  fileDesc("ChhwcmljaW5nX2NhbGN1bGF0b3IucHJvdG8iaQoIUHJpY2VSZXESDQoFbG90SUQYASACKAUSFgoOcmVtYWluaW5nU3BvdHMYAiACKAUSEgoKdG90YWxTcG90cxgDIAIoBRIQCghkYXRldGltZRgEIAIoCRIQCghkdXJhdGlvbhgFIAIoBSIaCglQcmljZVJlc3ASDQoFcHJpY2UYASABKAIyOQoSUHJpY2luZ19DYWxjdWxhdG9yEiMKCGdldFByaWNlEgkuUHJpY2VSZXEaCi5QcmljZVJlc3AiAA");

/**
 * Price Request specifies which lot and number of available spots. datetime is DD/MM/YYYY HH:MM, duration is in minutes
 *
 * @generated from message PriceReq
 */
export type PriceReq = Message<"PriceReq"> & {
  /**
   * @generated from field: required int32 lotID = 1;
   */
  lotID: number;

  /**
   * @generated from field: required int32 remainingSpots = 2;
   */
  remainingSpots: number;

  /**
   * @generated from field: required int32 totalSpots = 3;
   */
  totalSpots: number;

  /**
   * @generated from field: required string datetime = 4;
   */
  datetime: string;

  /**
   * @generated from field: required int32 duration = 5;
   */
  duration: number;
};

/**
 * Describes the message PriceReq.
 * Use `create(PriceReqSchema)` to create a new message.
 */
export const PriceReqSchema: GenMessage<PriceReq> = /*@__PURE__*/
  messageDesc(file_pricing_calculator, 0);

/**
 * Price Response returns a single price for the whole lot
 *
 * @generated from message PriceResp
 */
export type PriceResp = Message<"PriceResp"> & {
  /**
   * @generated from field: optional float price = 1;
   */
  price: number;
};

/**
 * Describes the message PriceResp.
 * Use `create(PriceRespSchema)` to create a new message.
 */
export const PriceRespSchema: GenMessage<PriceResp> = /*@__PURE__*/
  messageDesc(file_pricing_calculator, 1);

/**
 * @generated from service Pricing_Calculator
 */
export const Pricing_Calculator: GenService<{
  /**
   * Client Interface requests a price for a spot
   *
   * @generated from rpc Pricing_Calculator.getPrice
   */
  getPrice: {
    methodKind: "unary";
    input: typeof PriceReqSchema;
    output: typeof PriceRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_pricing_calculator, 0);

