/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v7.34.1
// source: pricing_calculator.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as pricing_calculator_pb from './pricing_calculator_pb'; // proto import: "pricing_calculator.proto"


export class Pricing_CalculatorClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorgetPrice = new grpcWeb.MethodDescriptor(
    '/Pricing_Calculator/getPrice',
    grpcWeb.MethodType.UNARY,
    pricing_calculator_pb.PriceReq,
    pricing_calculator_pb.PriceResp,
    (request: pricing_calculator_pb.PriceReq) => {
      return request.serializeBinary();
    },
    pricing_calculator_pb.PriceResp.deserializeBinary
  );

  getPrice(
    request: pricing_calculator_pb.PriceReq,
    metadata?: grpcWeb.Metadata | null): Promise<pricing_calculator_pb.PriceResp>;

  getPrice(
    request: pricing_calculator_pb.PriceReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: pricing_calculator_pb.PriceResp) => void): grpcWeb.ClientReadableStream<pricing_calculator_pb.PriceResp>;

  getPrice(
    request: pricing_calculator_pb.PriceReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: pricing_calculator_pb.PriceResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Pricing_Calculator/getPrice',
        request,
        metadata || {},
        this.methodDescriptorgetPrice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Pricing_Calculator/getPrice',
    request,
    metadata || {},
    this.methodDescriptorgetPrice);
  }

}

