/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v7.34.1
// source: transaction_handler.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as transaction_handler_pb from './transaction_handler_pb'; // proto import: "transaction_handler.proto"


export class Transaction_HandlerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptormakePayment = new grpcWeb.MethodDescriptor(
    '/Transaction_Handler/makePayment',
    grpcWeb.MethodType.UNARY,
    transaction_handler_pb.transReq,
    transaction_handler_pb.transResp,
    (request: transaction_handler_pb.transReq) => {
      return request.serializeBinary();
    },
    transaction_handler_pb.transResp.deserializeBinary
  );

  makePayment(
    request: transaction_handler_pb.transReq,
    metadata?: grpcWeb.Metadata | null): Promise<transaction_handler_pb.transResp>;

  makePayment(
    request: transaction_handler_pb.transReq,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: transaction_handler_pb.transResp) => void): grpcWeb.ClientReadableStream<transaction_handler_pb.transResp>;

  makePayment(
    request: transaction_handler_pb.transReq,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: transaction_handler_pb.transResp) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Transaction_Handler/makePayment',
        request,
        metadata || {},
        this.methodDescriptormakePayment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Transaction_Handler/makePayment',
    request,
    metadata || {},
    this.methodDescriptormakePayment);
  }

}

