// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file transaction_handler.proto (syntax proto2)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file transaction_handler.proto.
 */
export const file_transaction_handler: GenFile = /*@__PURE__*/
  fileDesc("Chl0cmFuc2FjdGlvbl9oYW5kbGVyLnByb3RvIkgKCHRyYW5zUmVxEg0KBXJlc0lEGAEgAigJEhMKC3BheW1lbnRJbmZvGAIgAigJEgsKA3VJRBgDIAIoCRILCgN2YWwYBCACKAkiSQoJdHJhbnNSZXNwEg0KBXJlc0lEGAEgAigJEg8KB3RyYW5zSUQYAiACKAkSCwoDdUlEGAMgAigJEg8KB3N1Y2Nlc3MYBCACKAgyPQoTVHJhbnNhY3Rpb25fSGFuZGxlchImCgttYWtlUGF5bWVudBIJLnRyYW5zUmVxGgoudHJhbnNSZXNwIgA");

/**
 * Consists of IDs for the user and reservation, payment info, and the value of the transaction
 *
 * @generated from message transReq
 */
export type transReq = Message<"transReq"> & {
  /**
   * @generated from field: required string resID = 1;
   */
  resID: string;

  /**
   * @generated from field: required string paymentInfo = 2;
   */
  paymentInfo: string;

  /**
   * @generated from field: required string uID = 3;
   */
  uID: string;

  /**
   * @generated from field: required string val = 4;
   */
  val: string;
};

/**
 * Describes the message transReq.
 * Use `create(transReqSchema)` to create a new message.
 */
export const transReqSchema: GenMessage<transReq> = /*@__PURE__*/
  messageDesc(file_transaction_handler, 0);

/**
 * Consists of reservation and user ID, and the generated transaction ID, and a success/fail indicator
 *
 * @generated from message transResp
 */
export type transResp = Message<"transResp"> & {
  /**
   * @generated from field: required string resID = 1;
   */
  resID: string;

  /**
   * @generated from field: required string transID = 2;
   */
  transID: string;

  /**
   * @generated from field: required string uID = 3;
   */
  uID: string;

  /**
   * @generated from field: required bool success = 4;
   */
  success: boolean;
};

/**
 * Describes the message transResp.
 * Use `create(transRespSchema)` to create a new message.
 */
export const transRespSchema: GenMessage<transResp> = /*@__PURE__*/
  messageDesc(file_transaction_handler, 1);

/**
 * @generated from service Transaction_Handler
 */
export const Transaction_Handler: GenService<{
  /**
   * Makes a payment for a reservation
   *
   * @generated from rpc Transaction_Handler.makePayment
   */
  makePayment: {
    methodKind: "unary";
    input: typeof transReqSchema;
    output: typeof transRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_transaction_handler, 0);

